packages:
  - client
  - processing
  - search
  - constants
  - utils
  - types
onlyBuiltDependencies:
  - better-sqlite3
  - esbuild
catalog:
  flexsearch: ^0.8.161
  typescript: ^5.3.3
  better-sqlite3: ^11.10.0
  '@types/better-sqlite3': ^7.6.13
