packages:
  - packages/client
  - packages/processing
  - packages/search
  - packages/constants
  - packages/utils
  - packages/types
onlyBuiltDependencies:
  - esbuild
  - sqlite3
catalog:
  flexsearch: ^0.8.161
  typescript: ^5.3.3
