packages:
  - packages/client
  - packages/config
  - packages/constants
  - packages/logging
  - packages/database
  - packages/s3
  - packages/types
  - packages/ingestion/rss-retrieval-lambda
  - packages/ingestion/process-audio-lambda
  - packages/ingestion/srt-indexing-lambda
  - packages/search/search-lambda
catalog:
  '@orama/orama': ^3.1.7
  '@orama/plugin-data-persistence': ^3.1.7
  typescript: ^5.3.3
  '@aws-sdk/client-lambda': ^3.787.0
  '@aws-sdk/client-s3': ^3.787.0
  '@aws-sdk/credential-provider-sso': ^3.787.0
  '@aws-sdk/lib-storage': ^3.787.0
  '@aws-sdk/s3-request-presigner': ^3.787.0
  fs-extra: ^11.3.0
  '@types/fs-extra': ^11.0.4
  loglevel: ^1.9.2
  rolldown: ^1.0.0-beta.8
  tsx: ^4.7.0
onlyBuiltDependencies:
  - esbuild
  - rolldown
injectWorkspacePackages: true
