packages:
  - packages/client
  - packages/processing
  - packages/search
  - packages/constants
  - packages/logging
  - packages/database
  - packages/s3
  - packages/types
  - packages/ingestion/rss-retrieval-lambda
catalog:
  flexsearch: ^0.8.161
  typescript: ^5.3.3
  '@aws-sdk/client-s3': ^3.787.0
  '@aws-sdk/credential-provider-sso': ^3.787.0
  '@aws-sdk/s3-request-presigner': ^3.787.0
  fs-extra: ^11.3.0
  '@types/fs-extra': ^11.0.4
  loglevel: ^1.9.2
  sqlite3: ^5.1.7


onlyBuiltDependencies:
  - esbuild
  - sqlite3
injectWorkspacePackages: true