name: Destroy Dev Environment

on:
  workflow_dispatch:
    inputs:
      confirmation:
        description: 'Type "destroy-dev" to confirm destroying the dev environment'
        required: true
        type: string

permissions:
  contents: read
  id-token: write

jobs:
  terraform:
    name: Terraform Destroy Dev
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.confirmation == 'destroy-dev' }}
    defaults:
      run:
        working-directory: terraform
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.0.0

      - name: Terraform Init
        run: terraform init
      
      - name: Terraform Destroy
        run: |
          terraform destroy -auto-approve \
            -var-file=environments/dev.tfvars \
            -var="openai_api_key=${{ secrets.OPENAI_API_KEY }}" 